# Generated by Django 5.2.7 on 2025-10-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for SEO (must be unique).', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
