# Generated by Django 5.2.7 on 2025-10-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for SEO (must be unique).', max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product.', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10, verbose_name='price')),
                ('photo', models.ImageField(blank=True, help_text='Image of the product.', upload_to='products/', verbose_name='photo')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Current stock level of the product.', verbose_name='stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category to which this product belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
