# Generated by Django 5.2.7 on 2025-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product.', max_length=200, verbose_name='name'),
        ),
    ]
